### ISSUE TITLE
the Storage MK. III‘s ID

### ISSUE THREAD

**Issue by ji-xingling** [HarriXS/DSP-Mods#1]
I wonder if you have noticed that the ID of the new item is the same as that of the Interstellar Logistics Station，This made it impossible for me to copy Interstellar Logistics Station at all，So can you modify the ID of the new item so that it doesn't conflict with other items

**Comment by ji-xingling** [comment]
The problem is solved，I don't know whether ldbtool automatically added the ID to your item or the ID you set. If you set the ID, I hope you can make a correction to it，2103 is the ID of interstellar logistics station。

**Comment by HarriXS** [comment]
Yeah, thanks for letting me know, the ID was an (incredibly stupid) oversight on my part, but it should be fixed in the latest update.
