### ISSUE TITLE
More mods please)

### ISSUE THREAD

**Issue by calverst** [HarriXS/DSP-Mods#2]
Your mods are great. Very clean code!
The way i see DSP is - factorio for kids. I have 2 kids myself, and factorio seem a bit excessive for them, but DSP seem perfect.
The only thing i don't like is a late game grind. So, i think factories needs to be boosted. Instead of 0.75; 1; 1.5 the factory output should be 0.75; 2; 6. Maybe to modify recipies as well - use 4 factories of previous level instead of 1.
Next one are chem labs. lvl 1 chem lab should use 2 processors instead of 2 chips (since they aim at yellow science). And lvl 2 is 4x the speed. Uses 4 labs lvl 1, 8 HS glasss, 8 HS titanium, 2 quantum processors.

**Comment by HarriXS** [comment]
I do not plan on making any balance changing mods for now, but if I ever do, I'll consider it
