### ISSUE TITLE
Suggestion: [More Smelters] 建议：[更多冶炼厂]

### ISSUE THREAD

**Issue by Karmacopper** [HarriXS/DSP-Mods#7]
Currently, you cannot visually differentiate between a vanilla smelter and your modded version. Please recolour your modded smelters.

当前，您无法从视觉上区分香草冶炼厂和改装厂。请为改装后的冶炼厂重新着色。

**Comment by HarriXS** [comment]
I am not currently able to create new models for the smelters since I do not know how. But when I do learn how, it will be my top priority
